### ISSUE TITLE
Mettre en place des premiers composants UI pour nos entités

### ISSUE THREAD

**Issue by iammouadagr** [iammouadagr/ceri-m1-ecommerce-2022#5]

**Comment by iammouadagr** [comment]
@imanehacen  si tout est bon pour cette fonctionnalité on peut la clôturer ??

**Comment by iammouadagr** [comment]
@MohamedKharchouf t'en pense quoi ?

**Comment by imanehacen** [comment]
@iammouadagr pour cette étape je pense que oui

**Comment by iammouadagr** [comment]
Nickel !!
